version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:20.10.7

jobs:
  build_and_push:
    executor: docker-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t mgallai/vision_ai:v1 .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push mgallai/vision_ai:v1

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - main
