version: 2.1

executors:
  docker-executor:
    docker:
      - image: docker:20.10.7

jobs:
  build_and_push:
    executor: docker-executor
    steps:
      # Set up Docker environment for building images
      - setup_remote_docker:
          version: 20.10.7

      # Check out the code from the repository
      - checkout

      # Build the Docker image
      - run:
          name: Build Docker image
          command: docker build -t mgallai/vision_ai:${CIRCLE_SHA1} .

      # Log in to Docker Hub using credentials stored in CircleCI environment variables
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

      # Push Docker image
      - run:
          name: Push Docker image
          command: docker push mgallai/vision_ai:${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push:
          filters:
            branches:
              only:
                - main
