version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Print Docker Hub Username
          command: echo "Docker Hub Username is '$DOCKERHUB_USERNAME'"
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/visionai:${CIRCLE_SHA1} .
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/visionai:${CIRCLE_SHA1}

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: docker-branch
