version: 2.1

executors:
  docker-executor:
    docker:
      - image: mgallai/vision_ai:latest

jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run test_AI_NumberOfOutputs
          command: |
            . venv/bin/activate
            python -m unittest tests.test_AI_NumberOfOutputs
      - run:
          name: Run test_AI_PredictedCity
          command: |
            . venv/bin/activate
            python -m unittest tests.test_AI_PredictedCity
      - run:
          name: Run test_AI_Preprocessing
          command: |
            . venv/bin/activate
            python -m unittest tests.test_AI_Preprocessing
      - run:
          name: Run test_ButtonPanel
          command: |
            . venv/bin/activate
            python -m unittest tests.test_ButtonPanel
      - run:
          name: Run test_IconsExist
          command: |
            . venv/bin/activate
            python -m unittest tests.test_IconsExist
      - run:
          name: Run test_InformationDialog
          command: |
            . venv/bin/activate
            python -m unittest tests.test_InformationDialog
      - run:
          name: Run test_ModelExist
          command: |
            . venv/bin/activate
            python -m unittest tests.test_ModelExist
      - run:
          name: Run test_SelectMethod
          command: |
            . venv/bin/activate
            python -m unittest tests.test_SelectMethod
      - run:
          name: Run test_sort_button
          command: |
            . venv/bin/activate
            python -m unittest tests.test_sort_button

  build_and_push:
    docker:
      - image: docker:20.10.7
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t mgallai/vision_ai:latest .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push mgallai/vision_ai:latest

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
      - build_and_push:
          requires:
            - test
          filters:
            branches:
              only:
                - main
