version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  test:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -s tests

  build_and_push:
    docker:
      - image: docker:20.10.7
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t mgallai/vision_ai:$CIRCLE_SHA1 .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push mgallai/vision_ai:$CIRCLE_SHA1

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
